server:
  port: 18000

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss.SSS
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: INFIR@xabad.97
#    url: jdbc:mysql://140.143.201.219:4306/jyxd_patron_bebase?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: INFIR@xabad.97
          url: jdbc:mysql://140.143.201.219:4306/jyxd_patron_bebase?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
        icu:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: INFIR@xabad.97
          url: jdbc:mysql://140.143.201.219:4306/jyxd_health_icu?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    type: com.zaxxer.hikari.HikariDataSource


mybatis-plus:
  sql-log:
    enable: false
  global-config:
    banner: false
    db-config:
      id-type: auto
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

